@startuml
queue "RabbitMQ Broker" as RabbitMQ
participant "Chatbot Service" as Python
database "DB (Python)" as PythonDB
database "Cloudflare R2" as R2




== 1. TH: Tin nhắn Xóa Share đến trước Tạo Share ==
note over RabbitMQ, Python: Tin nhắn Xóa Share đến trước Tạo Share

RabbitMQ -> Python ++: Nhận dev_share_revoked
Python -> PythonDB ++: Truy vấn Share
PythonDB --> Python --: Trả về None (Chưa tồn tại)

note over Python: Xử lý Thu hồi ngay lập tức

Python -> R2 ++: Yêu cầu xóa file tĩnh trên Cloudflare R2 (Nếu có)
R2 --> Python --: OK
Python -> PythonDB ++: Lưu Share mới (is_revoked = True)
PythonDB --> Python --: OK
Python --> RabbitMQ --: Ack (Hoàn thành thu hồi ngay)

== 2. Nhận tin nhắn Tạo Share đến sau ==
note over RabbitMQ, Python: Nhận tin nhắn Tạo Share đến sau

RabbitMQ -> Python ++: Nhận dev_share_generated
Python -> PythonDB ++: Truy vấn Share
PythonDB --> Python --: Trả về Share (is_revoked = True)

note over Python: Phát hiện trạng thái is_revoked = True
note over Python: Hủy bỏ hành động tạo (Không upload R2)
Python --> RabbitMQ --: Ack (Đóng tin nhắn an toàn)
@enduml